Add a missing import
Fix Error:  /Users/runner/work/opengrok/opengrok/opengrok-web/src/main/java/org/opengrok/web/PageConfig.java:[1854,16] cannot find symbol
Error:    symbol:   variable Paths